# Based on https://github.com/docker/build-push-action

name: docker-build-push

on:
  push:
  schedule:
      # Run pipeline every Monday, Wednesday, Friday and Sunday at midnight
    - cron:  '0 0 * * 1,3,5,7'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: stianovrevage/grype-with-db:latest